services:
  bot:
    build:
      context: .
      dockerfile: dockerfile
    networks:
      - docker-service
    depends_on:
      mariadb:
        condition: service_started

  mariadb:
    image: mariadb:latest
    restart: 'always'
    ports:
      - 3306:3306
    networks:
      - docker-service
    volumes:
     - maria-data:/data/db
  
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}

networks:
  docker-service:
    driver: bridge

volumes:
  maria-data:
    driver: local